### ISSUE TITLE
as_list() is not defined on an unknown TensorShape？

### ISSUE THREAD

**Issue by butterflydisappeared** [google-research/morph-net#86] opened 2019-06-12 06:57 UTC
![image](https://user-images.githubusercontent.com/38245234/59329753-3dfe6f00-8d22-11e9-82cb-fbcc93ad9445.png)

Code：
`import tensorflow as tf
from morph_net.network_regularizers import flop_regularizer
from morph_net.network_regularizers import latency_regularizer
from morph_net.tools import structure_exporter
import numpy as np
from datetime import datetime
import time

def conv2d(input, w, b):
    return tf.nn.relu(tf.nn.bias_add(tf.nn.conv2d(input, w, strides=[1, 1, 1, 1], padding='SAME'),
                                     b))
def max_pool(input):
    return tf.nn.max_pool(input, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1],
                          padding='SAME')
def fc(input, w, b):
    return tf.nn.relu(tf.add(tf.matmul(input, w), b))

def alex_net(_input_r, _weights, _biases, _keep_prob):
    with tf.name_scope('conv1'):
        _conv1 = conv2d(_input_r, _weights['wc1'], _biases['bc1'])

    with tf.name_scope('pool1'):
        _pool1 = max_pool(_conv1)

    with tf.name_scope('conv2'):
        _conv2 = conv2d(_pool1, _weights['wc2'], _biases['bc2'])

    with tf.name_scope('pool2'):
        _pool2 = max_pool(_conv2)

    with tf.name_scope('conv3'):
        _conv3 = conv2d(_pool2, _weights['wc3'], _biases['bc3'])

    with tf.name_scope('conv4'):
        _conv4 = conv2d(_conv3, _weights['wc4'], _biases['bc4'])

    with tf.name_scope('conv5'):
        _conv5 = conv2d(_conv4, _weights['wc5'], _biases['bc5'])

    with tf.name_scope('pool3'):
        _pool3 = max_pool(_conv5)

    _densel = tf.reshape(_pool3,
                         [-1, _weights['wd1'].get_shape().as_list()[0]])
    with tf.name_scope('fc1'):
        _fc1 = fc(_densel, _weights['wd1'], _biases['bd1'])
        _fc1_drop = tf.nn.dropout(_fc1, _keep_prob)

    with tf.name_scope('fc2'):
        _fc2 = fc(_fc1_drop, _weights['wd2'], _biases['bd2'])
        _fc2_drop = tf.nn.dropout(_fc2, _keep_prob)

    with tf.name_scope('out'):
        _out = tf.add(tf.matmul(_fc2_drop, _weights['wd3']), _biases['bd3'])

    return _out

n_output = 10
learning_rate = 0.001
dropout = 0.75
train_data, test_data = tf.keras.datasets.mnist.load_data()
X_train, X_test = train_data[0], test_data[0]
Y_train, Y_test = train_data[1], test_data[1]
train_dir = "./Morph_save/"
print("CNN READY")

x = tf.placeholder(tf.float32, [None, 28, 28, 1])
y = tf.placeholder(tf.float32, [None, 10])
keep_prob = tf.placeholder(tf.float32)

weights = {

    'wc1': tf.Variable(tf.truncated_normal([3, 3, 1, 64], dtype=tf.float32, stddev=0.1), name='weights1'),
    'wc2': tf.Variable(tf.truncated_normal([3, 3, 64, 128], dtype=tf.float32, stddev=0.1), name='weights2'),
    'wc3': tf.Variable(tf.truncated_normal([3, 3, 128, 256], dtype=tf.float32, stddev=0.1), name='weights3'),
    'wc4': tf.Variable(tf.truncated_normal([3, 3, 256, 256], dtype=tf.float32, stddev=0.1), name='weights4'),
    'wc5': tf.Variable(tf.truncated_normal([3, 3, 256, 128], dtype=tf.float32, stddev=0.1), name='weights5'),
    'wd1': tf.Variable(tf.truncated_normal([4*4*128, 1024], dtype=tf.float32, stddev=0.1), name='weights_fc1'),
    'wd2': tf.Variable(tf.random_normal([1024, 1024], dtype=tf.float32, stddev=0.1), name='weights_fc2'),
    'wd3': tf.Variable(tf.random_normal([1024, n_output], dtype=tf.float32, stddev=0.1), name='weights_output')
}
biases = {
    'bc1': tf.Variable(tf.constant(0.0, shape=[64], dtype=tf.float32), trainable=True, name='biases1'),
    'bc2': tf.Variable(tf.constant(0.0, shape=[128], dtype=tf.float32), trainable=True, name='biases2'),
    'bc3': tf.Variable(tf.constant(0.0, shape=[256], dtype=tf.float32), trainable=True, name='biases3'),
    'bc4': tf.Variable(tf.constant(0.0, shape=[256], dtype=tf.float32), trainable=True, name='biases4'),
    'bc5': tf.Variable(tf.constant(0.0, shape=[128], dtype=tf.float32), trainable=True, name='biases5'),
    'bd1': tf.Variable(tf.constant(0.0, shape=[1024], dtype=tf.float32), trainable=True, name='biases_fc1'),
    'bd2': tf.Variable(tf.constant(0.0, shape=[1024], dtype=tf.float32), trainable=True, name='biases_fc2'),
    'bd3': tf.Variable(tf.constant(0.0, shape=[n_output], dtype=tf.float32), trainable=True, name='biases_output')
}
print("CNN READY")
pred = alex_net(x, weights, biases, keep_prob)
network_regularizer = flop_regularizer.GroupLassoFlopsRegularizer(output_boundary=[pred.op],input_boundary=[x.op, y.op],threshold=1e-3)
regularization_strength = 1e-8
regularizer_loss = (network_regularizer.get_regularization_term() * regularization_strength)
model_loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(y, pred))
cost_op = network_regularizer.get_cost()
optimizer = tf.train.MomentumOptimizer(learning_rate=0.01, momentum=0.9)
train_op = optimizer.minimize(model_loss + regularizer_loss)
exporter = structure_exporter.StructureExporter(network_regularizer.op_regularizer_manager)
init = tf.global_variables_initializer()
print("FUNCTIONS READY")

training_epochs = 1000
batch_size = 500
display_step = 10

sess = tf.Session()
sess.run(init)
for epoch in range(training_epochs):
    avg_cost = 0.
    total_batch = int(60000/batch_size)
    start_time = time.time()
    for i in range(total_batch):
        batch_xs, batch_ys = X_train[i*batch_size:i*batch_size+batch_size], Y_train[i*batch_size:i*batch_size+batch_size]

        _, get_cost, loss_val, regloss_val,  structure_exporter_tensors=\
            sess.run([train_op,cost_op,model_loss,regularizer_loss,exporter.tensors], feed_dict={x: batch_xs, y: batch_ys, keep_prob:dropout})

    if epoch % display_step == 0:
        train_accuracy = sess.run(model_loss, feed_dict={x: batch_xs, y: batch_ys, keep_prob: 1.0})
        test_accuracy = sess.run(model_loss, feed_dict={x: X_train, y: Y_test, keep_prob:1.0})
        exporter.populate_tensor_values(structure_exporter_tensors)
        exporter.create_file_and_save_alive_counts(train_dir, epoch)
        print("Epoch: %03d/%03d cost: %.9f TRAIN ACCURACY: %.3f TEST ACCURACY: %.3f" % (epoch, training_epochs, avg_cost, train_accuracy, test_accuracy))
    duration = time.time() - start_time
    print('%s: step %d, duration = %.3f' % (datetime.now(), epoch, duration))
print("DONE")

`

**Comment by eladeban** [comment] 2019-06-13 08:14
the problem is with
```
keep_prob = tf.placeholder(tf.float32)
```
try 
```
keep_prob = tf.placeholder(tf.float32,1)
```

also for latency regularizers you might need:
```
x = tf.placeholder(tf.float32, [batch_size, 28, 28, 1])
y = tf.placeholder(tf.float32, [batch_size, 10])
```
should work.

**Comment by eladeban** [comment] 2019-07-01 05:56
closing

**Closed by eladeban** 2019-07-01 05:56 UTC

**Comment by castillomartin** [comment] 2020-01-12 22:30
model_loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(labels=tf.argmax(y,1),logits=pred))

 --- ---- > labels=tf.argmax(y,1)

**Comment by yuping3252** [comment] 2021-04-26 20:46
I have the same error message, from a different situation:

My environment is tensorflow 2.0.0

When I check the dataset, using: print(dataset2)
the result is   <MapDataset shapes: (<unknown>, <unknown>), types: (tf.uint8, tf.float32)>

or if I take one cell in the dataset:

for d in dataset2:
    print(d)
   break

the result is:
(<tf.Tensor: id=664, shape=(32, 32, 3), dtype=uint8, numpy=
array([[[255, 255, 255],
        [253, 253, 253],
        [253, 253, 253],
        ...,
        [253, 253, 253],
     ...,
        [253, 253, 253],
        [253, 253, 253],
        [255, 255, 255]]], dtype=uint8)>, <tf.Tensor: id=665, shape=(3,), dtype=float32, numpy=array([0., 1., 0.], dtype=float32)>)

The statement in the code that generated this error is:
history = cifar_model.fit(train_dataset2, validation_data=test_dataset2, epochs=15)

The error message generated is very long, I won't copy it here, but the last a few lines are:

/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py in as_list(self)
   1169     """
   1170     if self._dims is None:
-> 1171       raise ValueError("as_list() is not defined on an unknown TensorShape.")
   1172     return [dim.value for dim in self._dims]
   1173 
ValueError: as_list() is not defined on an unknown TensorShape.  <------------------------ here, as_list() is not defined

So, I suspect the unknown shape played some role in causing this error. 

But logically, the shape information is there in the dataset, as you can see from the print out.

So, any suggestion to debug this thing? Appreciated

**Comment by yuping3252** [comment] 2021-04-27 00:38
I answer my own question.

The problem is not resolved yet. But I get a bit progress: I find that, if I use
dataset = tf.data.Dataset.from_tensor_sliced((data, labels))
to create a combined Dataset object, then
print(dataset)
will give out the the shape information.
(TensorSpec(shape=(32, 32, 3), dtype=tf.uint8, name=None), TensorSpec(shape=(1,), dtype=tf.int64, name=None))

But then I need to do some conversion to the label, i.e., second component, using dataset.map() function, and the shape information disappeared again. By the time I need to fit(....) the same error message appeared again.
